import smtplib
import sys
from email.message import EmailMessage
from email.utils import make_msgid, formatdate
from pathlib import Path
from src.dispatcher.config import SmtpConfig

def dispatch_epub_to_kindle(epub_path: Path | str, config: SmtpConfig) -> None:
    target_file = Path(epub_path).resolve()
    
    if not target_file.exists():
        raise FileNotFoundError(f"Artifact not located for dispatch: {target_file}")

    message = EmailMessage()
    message['Subject'] = f"Automated Kindle Dispatch: {target_file.name}"
    message['From'] = config.sender
    message['To'] = config.destination
    message['Message-ID'] = make_msgid(domain=config.host)
    message['Date'] = formatdate(localtime=True)
    message.set_content("EPUB artifact generated by automated conversion pipeline.")

    with open(target_file, 'rb') as file_descriptor:
        binary_payload = file_descriptor.read()

    message.add_attachment(
        binary_payload,
        maintype='application',
        subtype='epub+zip',
        filename=target_file.name
    )

    sys.stdout.write(f"Initiating SMTP connection to {config.host}:{config.port}...\n")
    try:
        with smtplib.SMTP(config.host, config.port) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            
            sys.stdout.write(f"Attempting authentication for user: {config.sender}...\n")
            server.login(config.sender, config.password)
            
            sys.stdout.write("Transmitting binary payload...\n")
            server.send_message(message)
            sys.stdout.write("Transmission successful. Destination MTA accepted the payload.\n")
                
    except smtplib.SMTPException as network_error:
        raise RuntimeError(
            f"SMTP protocol failure during state machine execution.\n"
            f"Protocol trace: {network_error}"
        ) from network_error
