import smtplib
import mimetypes
from email.message import EmailMessage
from pathlib import Path
from src.dispatcher.config import SmtpConfig

def dispatch_epub_to_kindle(
    epub_path: Path | str, 
    config: SmtpConfig, 
    smtp_host: str = "smtp.gmail.com", 
    smtp_port: int = 587
) -> None:
    target_file = Path(epub_path).resolve()
    
    if not target_file.exists():
        raise FileNotFoundError(f"Artifact not located for dispatch: {target_file}")

    message = EmailMessage()
    message['Subject'] = f"Automated Kindle Dispatch: {target_file.name}"
    message['From'] = config.sender
    message['To'] = config.destination
    message.set_content("EPUB artifact generated by automated conversion pipeline.")

    with open(target_file, 'rb') as file_descriptor:
        binary_payload = file_descriptor.read()

    message.add_attachment(
        binary_payload,
        maintype='application',
        subtype='epub+zip',
        filename=target_file.name
    )

    try:
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(config.sender, config.password)
            server.send_message(message)
    except smtplib.SMTPException as network_error:
        raise RuntimeError(
            f"SMTP dispatch failed during network transmission.\n"
            f"Protocol trace: {network_error}"
        ) from network_error
