import smtplib
import sys
import mimetypes
from email.message import EmailMessage
from email.utils import make_msgid, formatdate
from pathlib import Path
from src.dispatcher.config import SmtpConfig

def dispatch_artifact_to_kindle(artifact_path: Path | str, config: SmtpConfig) -> None:
    target_file = Path(artifact_path).resolve()
    
    if not target_file.exists():
        raise FileNotFoundError(f"Artifact not located for dispatch: {target_file}")

    # Dynamically resolve MIME type boundaries
    mime_type, _ = mimetypes.guess_type(target_file)
    if mime_type is None:
        if target_file.suffix == '.epub':
            mime_type = 'application/epub+zip'
        elif target_file.suffix == '.pdf':
            mime_type = 'application/pdf'
        else:
            mime_type = 'application/octet-stream'
            
    maintype, subtype = mime_type.split('/', 1)

    message = EmailMessage()
    message['Subject'] = f"Automated Kindle Dispatch: {target_file.name}"
    message['From'] = config.sender
    message['To'] = config.destination
    message['Message-ID'] = make_msgid(domain=config.host)
    message['Date'] = formatdate(localtime=True)
    message.set_content(f"Artifact ({subtype}) generated by automated conversion pipeline.")

    with open(target_file, 'rb') as file_descriptor:
        binary_payload = file_descriptor.read()

    message.add_attachment(
        binary_payload,
        maintype=maintype,
        subtype=subtype,
        filename=target_file.name
    )

    sys.stdout.write(f"Initiating SMTP connection to {config.host}:{config.port}...\n")
    try:
        with smtplib.SMTP(config.host, config.port) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            
            sys.stdout.write(f"Attempting authentication for user: {config.sender}...\n")
            server.login(config.sender, config.password)
            
            sys.stdout.write(f"Transmitting binary payload [{mime_type}]...\n")
            server.send_message(message)
            sys.stdout.write("Transmission successful. Destination MTA accepted the payload.\n")
                
    except smtplib.SMTPException as network_error:
        raise RuntimeError(
            f"SMTP protocol failure during state machine execution.\n"
            f"Protocol trace: {network_error}"
        ) from network_error
