import subprocess

import json
from nexus_schema import Document, Section, Paragraph, Metadata
from pathlib import Path

import sys
from pypdf import PdfReader

import tempfile
def convert_pdf_to_md(pdf_path: Path) -> Path:
    # Use the external convert submodule to convert a PDF to Markdown.
    convert_dir = Path("external/convert").resolve()
    cli_path = convert_dir / "cli.py"

    output_md_path = pdf_path.with_suffix(".json")
    result_stdout = "convert CLI not found or failed to execute."

    # Run the convert CLI
    if cli_path.exists():
        try:
            # Pass the arguments expected by the convert CLI.
            # Since it's a stub, we execute it anyway but generate a fallback using pypdf if it doesn't output anything.
            result = subprocess.run(
                [
                    sys.executable,
                    str(cli_path),
                    "convert",
                    "--input",
                    str(pdf_path),
                    "--output",
                    str(output_md_path),
                ],
                cwd=str(convert_dir),
                capture_output=True,
                text=True,
            )
            result_stdout = result.stdout
        except Exception as e:
            result_stdout = f"Execution error: {e}"

    # If the stub just prints "Converting PDF..." without generating a file, use pypdf as a temporary fallback.
    if not output_md_path.exists():
        text_content = f"# Extracted Content from {pdf_path.name}\n\n"
        text_content += "> **Note:** This is a basic text extraction fallback generated by `pypdf` because the advanced `convert` ML pipeline is currently a stub or under development.\n\n"
        
        try:
            reader = PdfReader(pdf_path)
            for i, page in enumerate(reader.pages):
                text_content += f"## Page {i + 1}\n\n"
                text = page.extract_text()
                if text:
                    text_content += text + "\n\n"
                else:
                    text_content += "*[No extractable text found on this page]*\n\n"
        except Exception as ex:
            text_content += f"\n*Error extracting text using fallback: {ex}*\n"
            
        text_content += f"\n---\n**convert CLI Output:**\n```\n{result_stdout}\n```"
        
        doc = Document(
            metadata=Metadata(title=pdf_path.name),
            sections=[Section(content=[Paragraph(text=text_content)])]
        )
        with open(output_md_path, "w", encoding="utf-8") as f:
            json.dump(doc.model_dump(), f, ensure_ascii=False, indent=2)

    return output_md_path
