import subprocess
from pathlib import Path
import tempfile
import sys

def convert_pdf_to_md(pdf_path: Path) -> Path:
    # Use the external spliter submodule to convert a PDF to Markdown.
    spliter_dir = Path("external/spliter").resolve()
    cli_path = spliter_dir / "cli.py"

    if not cli_path.exists():
        raise FileNotFoundError(f"spliter CLI not found at {cli_path}. Ensure the submodule is initialized.")

    output_md_path = pdf_path.with_suffix('.md')

    # Run the spliter CLI
    try:
        # Pass the arguments expected by the spliter CLI.
        # Since it's a stub, we execute it anyway but generate a placeholder if it doesn't output anything.
        result = subprocess.run(
            [sys.executable, str(cli_path), "convert", "--input", str(pdf_path), "--output", str(output_md_path)],
            cwd=str(spliter_dir),
            capture_output=True,
            text=True
        )

        # If the stub just prints "Converting PDF..." without generating a file, create a placeholder
        if not output_md_path.exists():
            with open(output_md_path, "w", encoding="utf-8") as f:
                f.write(f"# Extracted Content from {pdf_path.name}\n\n")
                f.write("This is a placeholder generated by the spliter integration wrapper since the spliter CLI is currently a stub.\n")
                f.write(f"\nCommand Output:\n```\n{result.stdout}\n```")

        return output_md_path
    except Exception as e:
        raise RuntimeError(f"Failed to execute spliter: {e}")
