import subprocess
from pathlib import Path

import sys
from pypdf import PdfReader


def convert_pdf_to_md(pdf_path: Path) -> Path:
    # Use the external spliter submodule to convert a PDF to Markdown.
    spliter_dir = Path("external/spliter").resolve()
    cli_path = spliter_dir / "cli.py"

    output_md_path = pdf_path.with_suffix(".md")
    result_stdout = "spliter CLI not found or failed to execute."

    # Run the spliter CLI
    if cli_path.exists():
        try:
            # Pass the arguments expected by the spliter CLI.
            # Since it's a stub, we execute it anyway but generate a fallback using pypdf if it doesn't output anything.
            result = subprocess.run(
                [
                    sys.executable,
                    str(cli_path),
                    "convert",
                    "--input",
                    str(pdf_path),
                    "--output",
                    str(output_md_path),
                ],
                cwd=str(spliter_dir),
                capture_output=True,
                text=True,
            )
            result_stdout = result.stdout
        except Exception as e:
            result_stdout = f"Execution error: {e}"

    # If the stub just prints "Converting PDF..." without generating a file, use pypdf as a temporary fallback.
    if not output_md_path.exists():
        with open(output_md_path, "w", encoding="utf-8") as f:
            f.write(f"# Extracted Content from {pdf_path.name}\n\n")
            f.write(
                "> **Note:** This is a basic text extraction fallback generated by `pypdf` because the advanced `spliter` ML pipeline is currently a stub or under development.\n\n"
            )

            try:
                reader = PdfReader(pdf_path)
                for i, page in enumerate(reader.pages):
                    f.write(f"## Page {i + 1}\n\n")
                    text = page.extract_text()
                    if text:
                        f.write(text + "\n\n")
                    else:
                        f.write("*[No extractable text found on this page]*\n\n")
            except Exception as ex:
                f.write(f"\n*Error extracting text using fallback: {ex}*\n")

            f.write(f"\n---\n**spliter CLI Output:**\n```\n{result_stdout}\n```")

    return output_md_path
